gazebo_ros_control:
  pid_gains:
    left_wheel:
      p: 10.0
      i: 0.0
      d: 0.0
    right_wheel:
      p: 10.0
      i: 0.0
      d: 0.0
    fl_wheel:
      p: 10.0
      i: 0.0
      d: 0.0
    fr_wheel:
      p: 10.0
      i: 0.0
      d: 0.0
    rl_wheel:
      p: 10.0
      i: 0.0
      d: 0.0
    rr_wheel:
      p: 10.0
      i: 0.0
      d: 0.0
    fl_castor_wheel:
      p: 10.0
      i: 0.0
      d: 0.0
    fr_castor_wheel:
      p: 10.0
      i: 0.0
      d: 0.0
    rl_castor_wheel:
      p: 10.0
      i: 0.0
      d: 0.0
    rr_castor_wheel:
      p: 10.0
      i: 0.0
      d: 0.0

